version: '3'
services:
  db:
    image: postgres:alpine
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "computer"

  lotus_backend:
    build: .
    depends_on: 
      - db